### ISSUE TITLE
How can I get proper desired_sparsity to make new .yaml file??

### ISSUE THREAD

**Issue by chhkang** [anonymous47823493/EagleEye#25]
Hello, I want to adjust this pruning into another network architecture. 
Please give some instruction for making .yaml file in compress_config folder. thank you.

**Comment by bezorro** [comment]
Hi chhkang, thanks for your attention.
We only support for MobileNetV1 & ResNet50 in this repo now.
Since the `pruning`(including `masking` & `thinning`) process is based on [distiller](https://github.com/IntelLabs/distiller), you can refer to the [tutorial.](https://intellabs.github.io/distiller/tutorial-struct_pruning.html) to see how to prune your own network.

In fact, we have an inner implementation of EagleEye that can support arbitrary network architecture which is based on DMMO(Dark Matter Model Optimization library) because there still some limitations when using  [distiller](https://github.com/IntelLabs/distiller). I hope the library to be released soon.

**Comment by chhkang** [comment]
Okay, thanks for answering.

**Comment by youngboy52** [comment]
Hi, I see that pruning in this script is based on distiller, and I'm wonder that whether distiller has supported Conv1d or not? Thank you~
